title: AFP
url: "https://atpar.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /afp

# Build settings
markdown: kramdown
#theme: minima

plugins:
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 2 versions

sass:
  add_charset: true
  style: :compressed

# build exec jekyll serve