contact: https://docs.google.com/forms/d/e/1FAIpQLScRI6-87ZwpBlFk44tTmJjnBnWK7LpeIaMQ85jAzId6gEYbKQ/viewform
github: https://github.com/atpar

sass:
  sass_dir: assets/styles
  style: :compressed

exclude:
  - .jekyll-cache/
